Public Preview Refresh, Release 0.8.0 (#118)

diff --git a/azurepipelines/adu-ubuntu-arm64-build.yml b/azurepipelines/adu-ubuntu-arm64-build.yml
--- a/azurepipelines/adu-ubuntu-arm64-build.yml
+++ b/azurepipelines/adu-ubuntu-arm64-build.yml
@@ -1,29 +1,34 @@
 variables:
-    version.major: 0
-    version.minor: 6
-    version.patch: 0
-    version.pre-release: "public-preview"
-    version.build: $[format('{0:yyyyMMdd}-{0:HHmmss}', pipeline.startTime)]
-    # Environment variables for all client builds:
-    ADUC_VERSION_MAJOR: $(version.major)
-    ADUC_VERSION_MINOR: $(version.minor)
-    ADUC_VERSION_PATCH: $(version.patch)
-    ADUC_VERSION_PRERELEASE: $(version.pre-release)
-    ADUC_VERSION_BUILD: $(version.build)
-    # DO requires gcc greater than 6 for c++17 support.
-    # gcc-8 matches what is built with poky warrior.
-    CC: gcc-8
-    CXX: g++-8
-  
+  version.major: 0
+  version.minor: 8
+  version.patch: 0
+  version.pre-release: "public-preview"
+  version.build: $[format('{0:yyyyMMdd}-{0:HHmmss}', pipeline.startTime)]
+  # Environment variables for all client builds:
+  ADUC_VERSION_MAJOR: $(version.major)
+  ADUC_VERSION_MINOR: $(version.minor)
+  ADUC_VERSION_PATCH: $(version.patch)
+  ADUC_VERSION_PRERELEASE: $(version.pre-release)
+  ADUC_VERSION_BUILD: $(version.build)
+  ADUC_DEBIAN_PACKAGE_ARCHITECTURE: "arm64"
+
+  ENABLE_ADU_TELEMETRY_REPORTING: true
+  # ADUC_BUILDER_IDENTIFIER will be set to "DU" short for Device Update by default, for Device Update-sourced builder
+  ADUC_BUILDER_IDENTIFIER: DU
+  # DO requires gcc greater than 6 for c++17 support.
+  # gcc-8 matches what is built with poky warrior.
+  CC: gcc-8
+  CXX: g++-8
+
 name: $(version.major).$(version.minor).$(version.patch)-$(version.pre-release)+$(version.build)
-  
+
 resources:
-- repo: self
+  - repo: self
 
 trigger:
   branches:
     include:
-      - master
+      - main
       - release/*
   paths:
     exclude:
@@ -32,17 +37,14 @@ trigger:
       - LICENSE.md
       - .clang-format
       - .cmake-format.json
-      - tools/*
       - docker/*
-      - scripts/*
 
 pr:
   branches:
     include:
-      - master
+      - main
       - release/*
-      - feature/*
-      # TODO(shiyipeng): Task 27290511: Debian arm32 64 pipeline - improve build time
+      # - feature/*
       #- dev/*
   paths:
     exclude:
@@ -55,25 +57,34 @@ pr:
       - docker/*
       - scripts/*
       - licenses/*
-  
-jobs:
-- job: BuildAduAgent
-  displayName: 'Build ADU Agent'
-  timeoutInMinutes: 360
-  cancelTimeoutInMinutes: 360
-  pool: ADUC-Linux
-  steps:
-  - task: ms.vss-governance-buildtask.governance-build-task-component-detection.ComponentGovernanceComponentDetection@0
-    displayName: 'Component Detection'
-    inputs:
-      sourceScanPath: src
-  
-  # QEMU must be registered before this pipeline runs, but restarting the build VM will deregister QEMU,
-  # So, we just need to run QEMU before kicking off this pipeline. 
-  # This is only an issue on the arm64 flavor since we aren't able to register QEMU as part of the docker
-  # image for this architecture, which is not the case for arm32.
 
-  - bash: |
+jobs:
+  - job: BuildAduAgent
+    displayName: "Build ADU Agent"
+    timeoutInMinutes: 360
+    cancelTimeoutInMinutes: 360
+    pool: aduc_1es_client_pool
+    steps:
+      - task: ms.vss-governance-buildtask.governance-build-task-component-detection.ComponentGovernanceComponentDetection@0
+        displayName: "Component Detection"
+        inputs:
+          sourceScanPath: src
+
+      - task: Docker@2
+        displayName: Login to ACR
+        inputs:
+          command: login
+          containerRegistry: aduccontainerregistry
+          repository: ubuntu1804-arm64
+
+      - task: Docker@2
+        displayName: Pull latest build image
+        inputs:
+          command: pull
+          containerRegistry: aduccontainerregistry
+          arguments: "aduccontainerregistry.azurecr.io/ubuntu1804-arm64:latest"
+
+      - bash: |
           echo "Running whoami"
           whoami
           echo "Register QEMU"
@@ -82,156 +93,69 @@ jobs:
           sudo docker ps -a
           echo "Listing current images"
           sudo docker images
-    displayName: 'Prebuild'
-    condition: always()
-
-  - bash: |
-          sudo docker build --pull --rm -f "docker/arm64/Dockerfile" -t adu-arm64-img:latest "docker/arm64"
-    displayName: 'Build docker image'
-
-  - bash: |
-          sudo docker run -d -t --rm -v $(Build.SourcesDirectory):/iot-hub-device-update -v ~/.gitconfig:/etc/.gitconfig --name arm64container adu-arm64-img:latest bash 
-    displayName: 'Run docker container'
-
-  - bash: |
-          sudo docker exec -w /iot-hub-device-update arm64container scripts/install-deps.sh --install-aduc-deps --install-packages
-    displayName: 'Install aduc dependencies in container'
-
-  - bash: |
-          sudo docker exec -w /iot-hub-device-update arm64container scripts/install-deps.sh --install-do-deps
-    displayName: 'Install DO SDK dependencies in container'
-
-    # do_access_token is defined as a secret variable.
-    # This token gives our pipeline access to DO's private github repos.
-    # When DO code is public, we will no longer need to use this access token.
-    # Here we use git configuration to 'hijack' the regular github repo URLs
-    # and replace them with the authenticated URLs.
-    # See https://git-scm.com/docs/git-config#Documentation/git-config.txt-urlltbasegtinsteadOf
-    # Before setting the various url insteadOf sections, we make sure the config is in a clean state.
-    # Any corrupted/invalid entries will prevent the clone from succeeding.
-    # The various git config commands will also fail to remove invalid entries,
-    # so we use sed instead.
-  - bash: |
-          sudo docker exec arm64container cp /etc/.gitconfig /iot-hub-device-update/.gitconfig
-          sudo docker exec arm64container sed -i -e '/^.*url.*https.*@github.com\/Microsoft\/.*$/d' -e '/^.*insteadOf.*https.*github.com\/Microsoft\/.*$/d' /iot-hub-device-update/.gitconfig
-          sudo docker exec arm64container cp -f /iot-hub-device-update/.gitconfig /etc/.gitconfig
-          sudo docker exec arm64container git config --global url."https://api:$DO_ACCESS_TOKEN@github.com/Microsoft/do-client.git".insteadOf "https://github.com/Microsoft/do-client.git"
-          sudo docker exec arm64container git config --global url."https://api:$DO_ACCESS_TOKEN@github.com/Microsoft/do-client".insteadOf "https://github.com/Microsoft/do-client"
-    displayName: 'Configure git credentials for DO inside container'
-    env: 
-      DO_ACCESS_TOKEN: $(do_access_token)
-
-  - bash: |
-          sudo docker exec -w /iot-hub-device-update arm64container scripts/install-deps.sh --install-do
-    displayName: 'Install DO SDK from source in container'
-
-    # Cleanup the entries we added to clone private repos.
-    # The various git config commands will also fail to remove invalid entries,
-    # so we use sed instead.
-  - bash: |
-          sudo docker exec arm64container cp /etc/.gitconfig /iot-hub-device-update/.gitconfig
-          sudo docker exec arm64container sed -i -e '/^.*url.*https.*github.com\/Microsoft\/.*$/d' -e '/^.*insteadOf.*https.*github.com\/Microsoft\/.*$/d' /iot-hub-device-update/.gitconfig
-          sudo docker exec arm64container cp -f /iot-hub-device-update/.gitconfig /etc/.gitconfig
-    displayName: 'Remove git credentials for DO in container'
-    condition: succeededOrFailed()
-
-  - bash: |
-          sudo docker exec -w /iot-hub-device-update arm64container scripts/build.sh --clean --build-unit-tests --platform-layer simulator --content-handlers microsoft/swupdate --log-lib zlog --static-analysis clang-tidy,cppcheck --out-dir out-arm64
-    displayName: 'Build Client and Unit Tests: simulator-swupdate-Debug'
-
-    # note, -o param in the dependencies script adds a src/agent to the final location of AducIotAgent
-  - bash: |
-          cp out-arm64/src/agent/out-arm64/bin/AducIotAgent $(Build.ArtifactStagingDirectory)/AducIotAgentSim-microsoft-swupdate
-    displayName: 'Stage build artifacts (simulator-swupdate-debug)'
-    condition: and(ne(variables['Build.Reason'], 'IndividualCI'), ne(variables['Build.Reason'], 'PullRequest'))
-
-  - bash: |
-          sudo docker exec -w /iot-hub-device-update/out-arm64 arm64container ctest -T test -V --output-on-failure
-    displayName: 'Run Unit Tests: simulator-swupdate-Debug'
-
-  - task: PublishTestResults@2
-    displayName: 'Publish Unit Test Results: simulator-swupdate-Debug'
-    condition: succeededOrFailed() # Run this task even if tests fail.
-    inputs:
-      testResultsFormat: cTest
-      testResultsFiles: 'Testing/**/*.xml'
-      searchFolder: out-arm64
-      failTaskOnFailedTests: true
-      publishRunAttachments: false # Attachments are not supported for CTest
-
-  - bash: |
-          sudo docker exec -w /iot-hub-device-update arm64container scripts/build.sh --clean --provision-with-iotedge --platform-layer simulator --content-handlers microsoft/apt --log-lib zlog --out-dir out-arm64
-    displayName: 'Build Client: simulator-apt-Debug'
-
-    # note, -o param in the dependencies script adds a src/agent to the final location of AducIotAgent
-  - bash: |
-          cp out-arm64/src/agent/out-arm64/bin/AducIotAgent $(Build.ArtifactStagingDirectory)/AducIotAgentSim-microsoft-apt
-    displayName: 'Stage build artifacts (simulator-apt-debug)'
-    condition: and(ne(variables['Build.Reason'], 'IndividualCI'), ne(variables['Build.Reason'], 'PullRequest'))
-
-  - bash: |
-          sudo docker exec -w /iot-hub-device-update arm64container scripts/build.sh --clean --build-unit-tests --provision-with-iotedge --type MinSizeRel --platform-layer linux --content-handlers microsoft/apt --log-lib zlog --build-packages --static-analysis clang-tidy,cppcheck --out-dir out-arm64
-    displayName: 'Build Client, Unit Tests and Packages: linux-apt-MinSizeRel'
-    
-  - bash: |
+        displayName: "Prebuild"
+        condition: always()
+      - bash: |
+          sudo docker run -d -t --rm -v $(Build.SourcesDirectory):/iot-hub-device-update -v ~/.gitconfig:/etc/.gitconfig --name arm64container aduccontainerregistry.azurecr.io/ubuntu1804-arm64:latest bash
+        displayName: "Run docker container"
+      - bash: |
+          sudo docker exec -w /iot-hub-device-update arm64container scripts/build.sh --clean --build-unit-tests --type MinSizeRel --platform-layer linux --log-lib zlog --build-packages --static-analysis clang-tidy,cppcheck --out-dir out-arm64
+        displayName: "Build Client, Unit Tests and Packages: linux-apt-MinSizeRel"
+      - bash: |
           cp out-arm64/*.deb $(Build.ArtifactStagingDirectory)
           cp out-arm64/src/agent/out-arm64/bin/AducIotAgent $(Build.ArtifactStagingDirectory)/AducIotAgent
-    displayName: 'Stage build artifacts (Deb package, agent and docs)'
-    condition: and(ne(variables['Build.Reason'], 'IndividualCI'), ne(variables['Build.Reason'], 'PullRequest'))
-
-  - bash: |
+        displayName: "Stage build artifacts (Deb package, agent and docs)"
+        condition: and(ne(variables['Build.Reason'], 'IndividualCI'), ne(variables['Build.Reason'], 'PullRequest'))
+      - bash: |
           sudo docker exec -w /iot-hub-device-update/out-arm64 arm64container ctest -T test -V --output-on-failure
-    displayName: 'Run Unit Tests: linux-apt-MinSizeRel'
+        displayName: "Run Unit Tests: linux-apt-MinSizeRel"
+      - task: PublishTestResults@2
+        displayName: "Publish Unit Test Results: linux-apt-MinSizeRel"
+        condition: succeededOrFailed() # Run this task even if tests fail.
+        inputs:
+          testResultsFormat: cTest
+          testResultsFiles: "Testing/**/*.xml"
+          searchFolder: out-arm64
+          failTaskOnFailedTests: true
+          publishRunAttachments: false # Attachments are not supported for CTest
 
-  - task: PublishTestResults@2
-    displayName: 'Publish Unit Test Results: linux-apt-MinSizeRel'
-    condition: succeededOrFailed() # Run this task even if tests fail.
-    inputs:
-      testResultsFormat: cTest
-      testResultsFiles: 'Testing/**/*.xml'
-      searchFolder: out-arm64
-      failTaskOnFailedTests: true
-      publishRunAttachments: false # Attachments are not supported for CTest
-
-  - bash: |
-          sudo docker exec -w /iot-hub-device-update arm64container scripts/build.sh --clean --build-unit-tests --platform-layer linux --content-handlers microsoft/swupdate --log-lib zlog --static-analysis clang-tidy,cppcheck --out-dir out-arm64
-    displayName: 'Build Client and Unit Tests: linux-swupdate-Debug'
-
-  - bash: |
+      - bash: |
+          sudo docker exec -w /iot-hub-device-update arm64container scripts/build.sh --clean --build-unit-tests --platform-layer linux --log-lib zlog --static-analysis clang-tidy,cppcheck --out-dir out-arm64
+        displayName: "Build Client and Unit Tests: linux-Debug"
+      - bash: |
           sudo docker exec -w /iot-hub-device-update/out-arm64 arm64container ctest -T test -V --output-on-failure
-    displayName: 'Run Unit Tests: linux-swupdate-Debug'
+        displayName: "Run Unit Tests: linux-Debug"
+      - task: PublishTestResults@2
+        displayName: "Publish Unit Test Results: linux-Debug"
+        condition: succeededOrFailed() # Run this task even if tests fail.
+        inputs:
+          testResultsFormat: cTest
+          testResultsFiles: "Testing/**/*.xml"
+          searchFolder: out-arm64
+          failTaskOnFailedTests: true
+          publishRunAttachments: false # Attachments are not supported for CTest
 
-  - task: PublishTestResults@2
-    displayName: 'Publish Unit Test Results: linux-swupdate-Debug'
-    condition: succeededOrFailed() # Run this task even if tests fail.
-    inputs:
-      testResultsFormat: cTest
-      testResultsFiles: 'Testing/**/*.xml'
-      searchFolder: out-arm64
-      failTaskOnFailedTests: true
-      publishRunAttachments: false # Attachments are not supported for CTest
+      - task: PublishPipelineArtifact@0
+        displayName: "Publish Pipeline Artifacts"
+        condition: and(succeeded(), ne(variables['Build.Reason'], 'IndividualCI'), ne(variables['Build.Reason'], 'PullRequest'))
+        inputs:
+          artifactName: "adu-arm64-client"
+          targetPath: "$(Build.ArtifactStagingDirectory)"
 
-  - task: PublishPipelineArtifact@0
-    displayName: 'Publish Pipeline Artifacts'
-    condition: and(succeeded(), ne(variables['Build.Reason'], 'IndividualCI'), ne(variables['Build.Reason'], 'PullRequest'))
-    inputs:
-      artifactName: 'adu-arm64-client'
-      targetPath: '$(Build.ArtifactStagingDirectory)'
-
-    # Ignore SC2164: Use 'cd ... || exit' or 'cd ... || return' in case cd fails.
-    #   We usually want to return an error code from a specific, previous command
-    #   even if popd, pushd, or cd fails.
-    # Ignore SC2209: Use var=$(command) to assign output (or quote to assign string).
-    #   We use 'ret=return' or 'ret=exit' to support dot sourcing.
-  - bash: |
+        # Ignore SC2164: Use 'cd ... || exit' or 'cd ... || return' in case cd fails.
+        #   We usually want to return an error code from a specific, previous command
+        #   even if popd, pushd, or cd fails.
+        # Ignore SC2209: Use var=$(command) to assign output (or quote to assign string).
+        #   We use 'ret=return' or 'ret=exit' to support dot sourcing.
+      - bash: |
+          sudo apt-get install -y shellcheck
           shellcheck -s bash -e SC2164 -e SC2209 $(find -name "*.sh")
           exit $?
-    displayName: ' Run ShellCheck'
-
-    # Stop the running container at the end of the build job
-    # Remove output directory to prevent persisting across build jobs
-  - bash: |
-        sudo docker stop arm64container
-        sudo rm -rf out-arm64
-    displayName: 'Postbuild'
-    condition: always()
+        displayName: " Run ShellCheck"
+        # Stop the running container at the end of the build job
+        # Remove output directory to prevent persisting across build jobs
+      - bash: |
+          sudo docker stop arm64container
+          sudo rm -rf out-arm64
+        displayName: "Postbuild"
+        condition: always()
diff --git a/packages/debian/preinst b/packages/debian/preinst
--- a/packages/debian/preinst
+++ b/packages/debian/preinst
@@ -5,6 +5,7 @@
 # Creates and configures necessary users and groups for ADU.
 # Runs before installing/unpacking the debian package.
 # See https://www.debian.org/doc/debian-policy/ch-maintainerscripts.html
+#     https://www.debian.org/doc/debian-policy/ap-flowcharts.html
 
 echo "******************** Running $0 $1 $2 ***********************"
 
@@ -20,16 +21,81 @@ adu_user=adu
 # access to ADU resources like download sandbox folder.
 adu_group=adu
 
+# The location of the ADU configuration file pre-PPR (public preview refresh)
+pre_ppr_conf_file='/etc/adu/adu-conf.txt'
+
+# The path to the main ADU Agent binary.
+agent_file='/usr/bin/AducIotAgent'
+
+# The debian package name
+agent_deb_pkg_name='deviceupdate-agent'
+
+# The message to print for remediation of the upgrade.
+upgrade_remediation_step_message=''
+
+#
+# exit codes
+#
+exitcode_success=0
+exitcode_adu_group_already_exists=1
+exitcode_adu_user_already_exists=2
+exitcode_pre_ppr_installed=3 # pre-ppr agent binary is installed
+exitcode_pre_ppr_unpurged=4  # pre-ppr config exists
+exitcode_unknown_argument=5
+
+#
+# Prints an error message for failed upgrade due to presence of pre-PPR(public
+# preview refresh) installed binary or unpurged configuration.
+#
+# Pre-condition: must set upgrade_remediation_step_message before calling.
+#
+print_pre_ppr_error_message () {
+    echo "============================================================"
+    echo
+    echo "    Upgrade Failed."
+    echo
+    echo "    Before installing,"
+    echo "    ${upgrade_remediation_step_message}."
+    echo
+    echo "    After install, in the Azure portal, create a brand new device and"
+    echo "    add it to a new device group."
+    echo
+    echo "============================================================"
+}
+
+check_pre_ppr_agent_installed_or_unpurged () {
+    if [ -f "$agent_file" ]; then
+        agent_ver=$("$agent_file" --version)
+        echo "Existing DU Agent version: $agent_ver"
+
+        ver1=${agent_ver%%.*}
+        ver2=${agent_ver#${ver1}.}
+        ver2=${ver2%%.*}
+
+        if [ "$ver1" -eq 0 ] && [ "$ver2" -lt 8 ]; then
+            # Installed Agent binary is pre-PPR
+            upgrade_remediation_step_message="run 'sudo apt remove ${agent_deb_pkg_name}' and remove '${pre_ppr_conf_file}'"
+            print_pre_ppr_error_message
+            exit $exitcode_pre_ppr_installed
+        fi
+    elif [ -f "$pre_ppr_conf_file" ]; then
+        # Found non-purged pre-ppr upgrade
+        upgrade_remediation_step_message="remove '${pre_ppr_conf_file}'"
+        print_pre_ppr_error_message
+        exit $exitcode_pre_ppr_unpurged
+    fi
+}
+
 add_adu_user_and_group() {
     echo "Create the 'adu' group."
     if ! getent group "$adu_group" > /dev/null; then
         addgroup --system "$adu_group"
     else
         # For security purposes, it's extremely important that there's no existing 'adu' user and 'adu' group.
-        # This ensures the account and group are setup by our package installation process only, 
+        # This ensures the account and group are setup by our package installation process only,
         # and no other actor can pre-create the user/group with nefarious intentions.
         echo "Error: 'adu' group already exists." >&2
-        exit 1
+        exit $exitcode_adu_group_already_exists
     fi
 
     echo "Create the 'adu' user." # With no shell and no login, in 'adu' group.
@@ -37,24 +103,31 @@ add_adu_user_and_group() {
         adduser --system "$adu_user" --ingroup "$adu_group" --no-create-home --shell /bin/false
     else
         # For security purposes, it's extremely important that there's no existing 'adu' user and 'adu' group.
-        # This to ensures the account and group are setup by our package installation process only, 
+        # This to ensures the account and group are setup by our package installation process only,
         # and no other actor can pre-create the user/group with nefarious intentions.
         echo "Error: 'adu' user already exists." >&2
-        exit 2
+        exit $exitcode_adu_user_already_exists
     fi
 
     echo "Add the 'adu' user to the 'syslog' group." # To allow ADU to write to /var/log folder
-    usermod -aG "syslog" "$adu_user" 
+    if getent group "syslog" > /dev/null; then
+        usermod -aG "syslog" "$adu_user"
+    fi
 }
 
 case "$1" in
     install)
+        # Disallow upgrade for non-purged pre-PPR agent.
+        check_pre_ppr_agent_installed_or_unpurged
+
         # Try to add user during 'preinst install' step.
         # If fail, the 'adu' user and group will be removed at 'postrm abort-install' task.
         add_adu_user_and_group
     ;;
 
     upgrade)
+        # Disallow upgrade for unpacked pre-PPR agent.
+        check_pre_ppr_agent_installed_or_unpurged
     ;;
 
     abort-upgrade)
@@ -62,8 +135,8 @@ case "$1" in
 
     *)
         echo "preinst called with unknown argument \`$1'" >&2
-        exit 1
+        exit $exitcode_unknown_argument
     ;;
 esac
 
-exit 0
+exit $exitcode_success
